
-- Insert 20 new government jobs
INSERT INTO gov_jobs (title, department, category, notification_date, last_date, total_posts, qualification, age_limit, application_fee, eligibility, selection_process, apply_link, source, is_active) VALUES
('UPSC NDA/NA 2025 - National Defence Academy', 'Union Public Service Commission', 'Defence', '2025-06-01', '2025-07-15', '400', '12th Pass', '16.5-19.5 years', 'Rs. 100 (SC/ST Exempt)', '12th Pass from recognized board', 'Written Exam + SSB Interview', 'https://upsc.gov.in', 'sarkariresult.com', true),
('UPSC CAPF 2025 - Central Armed Police Forces', 'Union Public Service Commission', 'Defence', '2025-05-20', '2025-06-30', '322', 'Graduation', '20-25 years', 'Rs. 200 (SC/ST Exempt)', 'Graduate from recognized university', 'Written Exam + Physical Test + Interview', 'https://upsc.gov.in', 'sarkariresult.com', true),
('RBI Grade B Officer 2025', 'Reserve Bank of India', 'Banking', '2025-07-01', '2025-08-10', '150', 'Graduation', '21-30 years', 'Rs. 850', 'Graduate with 60% marks', 'Phase I + Phase II + Interview', 'https://rbi.org.in', 'sarkariresult.com', true),
('SEBI Officer Grade A 2025', 'Securities and Exchange Board of India', 'Finance', '2025-06-15', '2025-07-20', '97', 'Graduation/PG', '21-30 years', 'Rs. 1000', 'Graduate/PG in relevant discipline', 'Phase I + Phase II + Interview', 'https://sebi.gov.in', 'sarkariresult.com', true),
('NTA UGC NET June 2025', 'National Testing Agency', 'Education', '2025-03-15', '2025-04-30', 'Multiple', 'Post Graduation', 'No upper limit for JRF: 31', 'Rs. 1150 (Gen)', 'PG with 55% marks', 'Computer Based Test', 'https://ugcnet.nta.ac.in', 'sarkariresult.com', true),
('UPSC EPFO 2025 - Enforcement Officer', 'Union Public Service Commission', 'Government', '2025-07-10', '2025-08-15', '577', 'Graduation', '21-30 years', 'Rs. 200', 'Graduate from recognized university', 'Recruitment Test + Interview', 'https://upsc.gov.in', 'sarkariresult.com', true),
('Delhi Police Constable 2025', 'Staff Selection Commission', 'Police', '2025-04-01', '2025-05-15', '6433', '12th Pass', '18-25 years', 'Rs. 100', '12th Pass from recognized board', 'CBT + Physical + Medical', 'https://ssc.nic.in', 'sarkariresult.com', true),
('CISF Constable GD 2025', 'Central Industrial Security Force', 'Defence', '2025-05-01', '2025-06-15', '12000', '10th Pass', '18-23 years', 'Rs. 100', '10th Pass from recognized board', 'CBT + Physical + Medical', 'https://cisfrectt.in', 'sarkariresult.com', true),
('ESIC UDC & Stenographer 2025', 'Employees State Insurance Corporation', 'Government', '2025-06-20', '2025-07-25', '1934', 'Graduation', '18-27 years', 'Rs. 500', 'Graduate from recognized university', 'Prelims + Mains + Skill Test', 'https://esic.nic.in', 'sarkariresult.com', true),
('LIC AAO 2025 - Assistant Administrative Officer', 'Life Insurance Corporation', 'Insurance', '2025-08-01', '2025-09-05', '300', 'Graduation', '21-30 years', 'Rs. 700', 'Graduate with 60% marks', 'Prelims + Mains + Interview', 'https://licindia.in', 'sarkariresult.com', true),
('NABARD Grade A 2025', 'National Bank for Agriculture and Rural Development', 'Banking', '2025-07-15', '2025-08-20', '162', 'Graduation/PG', '21-30 years', 'Rs. 800', 'Graduate/PG in relevant field', 'Phase I + Phase II + Interview', 'https://nabard.org', 'sarkariresult.com', true),
('FCI Manager 2025 - Food Corporation of India', 'Food Corporation of India', 'Government', '2025-06-01', '2025-07-10', '5043', 'Graduation', '21-28 years', 'Rs. 800', 'Graduate from recognized university', 'CBT + Interview', 'https://fci.gov.in', 'sarkariresult.com', true),
('SSC CHSL 2025 - Combined Higher Secondary Level', 'Staff Selection Commission', 'Government', '2025-05-15', '2025-06-20', '4500', '12th Pass', '18-27 years', 'Rs. 100', '12th Pass from recognized board', 'CBT Tier I + Tier II', 'https://ssc.nic.in', 'sarkariresult.com', true),
('Indian Navy SSR/AA 2025 - Sailor Recruitment', 'Indian Navy', 'Defence', '2025-04-10', '2025-05-20', '2800', '12th Pass (Science)', '17-20 years', 'Nil', '12th with Maths and Physics', 'Written + Physical + Medical', 'https://joinindiannavy.gov.in', 'sarkariresult.com', true),
('UPPSC RO/ARO 2025 - Review Officer', 'UP Public Service Commission', 'State Government', '2025-06-25', '2025-07-30', '411', 'Graduation', '21-40 years', 'Rs. 125', 'Graduate from recognized university', 'Prelims + Mains + Interview', 'https://uppsc.up.nic.in', 'sarkariresult.com', true),
('MPSC State Services 2025', 'Maharashtra Public Service Commission', 'State Government', '2025-05-10', '2025-06-25', '1100', 'Graduation', '19-38 years', 'Rs. 524', 'Graduate from recognized university', 'Prelims + Mains + Interview', 'https://mpsc.gov.in', 'sarkariresult.com', true),
('BPSC 70th Combined Exam 2025', 'Bihar Public Service Commission', 'State Government', '2025-07-01', '2025-08-05', '2060', 'Graduation', '20-37 years', 'Rs. 600', 'Graduate from recognized university', 'Prelims + Mains + Interview', 'https://bpsc.bih.nic.in', 'sarkariresult.com', true),
('SSC MTS 2025 - Multi Tasking Staff', 'Staff Selection Commission', 'Government', '2025-04-20', '2025-05-25', '8326', '10th Pass', '18-25 years', 'Rs. 100 (SC/ST Exempt)', '10th Pass from recognized board', 'CBT + Physical', 'https://ssc.nic.in', 'sarkariresult.com', true),
('IBPS SO 2025 - Specialist Officer', 'Institute of Banking Personnel Selection', 'Banking', '2025-09-01', '2025-10-05', '710', 'Graduation/PG', '20-30 years', 'Rs. 850', 'Graduate/PG in relevant specialization', 'Prelims + Mains + Interview', 'https://ibps.in', 'sarkariresult.com', true),
('RPSC RAS 2025 - Rajasthan Administrative Service', 'Rajasthan Public Service Commission', 'State Government', '2025-06-10', '2025-07-15', '905', 'Graduation', '21-40 years', 'Rs. 350', 'Graduate from recognized university', 'Prelims + Mains + Interview', 'https://rpsc.rajasthan.gov.in', 'sarkariresult.com', true)
ON CONFLICT DO NOTHING;

-- Insert 14 new admissions
INSERT INTO gov_admissions (title, authority, category, notification_date, last_date, eligibility, application_fee, age_limit, selection_process, apply_link, source, is_active) VALUES
('NIT Trichy M.Tech Admission 2025', 'National Institute of Technology Trichy', 'Engineering', '2025-03-01', '2025-04-30', 'B.Tech/BE with valid GATE score', 'Rs. 500', 'No age limit', 'GATE Score + Interview', 'https://nitt.edu', 'sarkariresult.com', true),
('IIT Bombay PhD Admission 2025', 'Indian Institute of Technology Bombay', 'Research', '2025-03-15', '2025-05-15', 'M.Tech/ME with valid GATE/UGC NET', 'Rs. 200', 'No age limit', 'Written Test + Interview', 'https://iitb.ac.in', 'sarkariresult.com', true),
('AIIMS MBBS 2025 - INI CET', 'All India Institute of Medical Sciences', 'Medical', '2025-04-01', '2025-05-31', '12th with PCB, NEET qualified', 'Rs. 1500', '17-25 years', 'NEET UG Score', 'https://aiimsexams.ac.in', 'sarkariresult.com', true),
('Delhi University PG Admission 2025', 'University of Delhi', 'Post Graduation', '2025-05-01', '2025-06-30', 'Graduation with 50% marks', 'Rs. 750', 'No age limit', 'CUET PG Score', 'https://du.ac.in', 'sarkariresult.com', true),
('IIM CAT 2025 Registration', 'Indian Institutes of Management', 'Management', '2025-08-01', '2025-09-15', 'Graduation with 50% marks', 'Rs. 2400', 'No age limit', 'CAT Score + WAT/PI', 'https://iimcat.ac.in', 'sarkariresult.com', true),
('IGNOU January 2026 Admission', 'Indira Gandhi National Open University', 'Distance Education', '2025-10-01', '2025-12-31', 'Varies by program', 'Rs. 200', 'No age limit', 'Merit Based', 'https://ignou.ac.in', 'sarkariresult.com', true),
('JNU Entrance Exam 2025 - JNUEE', 'Jawaharlal Nehru University', 'University', '2025-03-10', '2025-04-20', 'Graduation for PG programs', 'Rs. 500', 'No age limit', 'CUET Based', 'https://jnu.ac.in', 'sarkariresult.com', true),
('BHU UET/PET 2025 Admission', 'Banaras Hindu University', 'University', '2025-04-15', '2025-05-30', '12th Pass / Graduation', 'Rs. 600', 'As per program', 'CUET Score', 'https://bhu.ac.in', 'sarkariresult.com', true),
('AMU Entrance Test 2025', 'Aligarh Muslim University', 'University', '2025-03-20', '2025-05-10', '12th Pass / Graduation', 'Rs. 600', 'No age limit', 'AMU Entrance Test', 'https://amu.ac.in', 'sarkariresult.com', true),
('NLU CLAT 2025 - Law Admission', 'Consortium of NLUs', 'Law', '2025-06-01', '2025-07-15', '12th Pass for UG / LLB for PG', 'Rs. 4000', 'No age limit for UG', 'CLAT Score', 'https://consortiumofnlus.ac.in', 'sarkariresult.com', true),
('TISS NET 2025 - Social Work Admission', 'Tata Institute of Social Sciences', 'Social Sciences', '2025-10-01', '2025-12-15', 'Graduation with 50% marks', 'Rs. 1100', 'No age limit', 'TISS NET + GD/PI', 'https://tiss.edu', 'sarkariresult.com', true),
('ISI Admission 2025 - Indian Statistical Institute', 'Indian Statistical Institute', 'Statistics/Math', '2025-02-15', '2025-04-10', '12th with Maths for B.Stat', 'Rs. 500', 'No age limit', 'Written Test + Interview', 'https://isical.ac.in', 'sarkariresult.com', true),
('NIFT Entrance 2025 - Fashion Technology', 'National Institute of Fashion Technology', 'Design', '2025-01-15', '2025-03-01', '12th Pass for UG', 'Rs. 3000', 'No age limit for UG', 'CAT + GAT + Situation Test', 'https://nift.ac.in', 'sarkariresult.com', true),
('IISC Bangalore Admission 2025', 'Indian Institute of Science', 'Science/Engineering', '2025-02-01', '2025-04-15', 'B.Sc/B.Tech with valid JAM/GATE', 'Rs. 800', 'No age limit', 'JAM/GATE Score + Interview', 'https://iisc.ac.in', 'sarkariresult.com', true)
ON CONFLICT DO NOTHING;

-- Insert 15 new admit cards
INSERT INTO gov_admit_cards (title, department, exam_date, admit_card_date, download_link, status, source, is_active) VALUES
('UPSC CSE Prelims 2025 Admit Card', 'Union Public Service Commission', '2025-06-01', '2025-05-15', 'https://upsc.gov.in', 'Available', 'sarkariresult.com', true),
('SSC CGL Tier-2 2025 Admit Card', 'Staff Selection Commission', '2025-07-10', '2025-06-25', 'https://ssc.nic.in', 'Available', 'sarkariresult.com', true),
('IBPS PO Prelims 2025 Admit Card', 'Institute of Banking Personnel Selection', '2025-10-05', '2025-09-20', 'https://ibps.in', 'Upcoming', 'sarkariresult.com', true),
('RRB NTPC CBT-1 2025 Admit Card', 'Railway Recruitment Board', '2025-08-15', '2025-08-01', 'https://rrbcdg.gov.in', 'Upcoming', 'sarkariresult.com', true),
('NTA NEET UG 2025 Admit Card', 'National Testing Agency', '2025-05-04', '2025-04-20', 'https://neet.nta.nic.in', 'Available', 'sarkariresult.com', true),
('NTA JEE Main 2025 Session 2 Admit Card', 'National Testing Agency', '2025-04-02', '2025-03-20', 'https://jeemain.nta.ac.in', 'Available', 'sarkariresult.com', true),
('CUET UG 2025 Admit Card', 'National Testing Agency', '2025-05-15', '2025-05-01', 'https://cuet.nta.nic.in', 'Available', 'sarkariresult.com', true),
('UGC NET June 2025 Admit Card', 'National Testing Agency', '2025-06-15', '2025-06-01', 'https://ugcnet.nta.ac.in', 'Upcoming', 'sarkariresult.com', true),
('GATE 2026 Admit Card', 'IIT Delhi', '2026-02-01', '2026-01-15', 'https://gate2026.iitd.ac.in', 'Upcoming', 'sarkariresult.com', true),
('CAT 2025 Admit Card', 'Indian Institutes of Management', '2025-11-24', '2025-11-05', 'https://iimcat.ac.in', 'Upcoming', 'sarkariresult.com', true),
('MPSC State Services Prelims 2025 Admit Card', 'Maharashtra Public Service Commission', '2025-07-20', '2025-07-05', 'https://mpsc.gov.in', 'Upcoming', 'sarkariresult.com', true),
('BPSC 70th Prelims 2025 Admit Card', 'Bihar Public Service Commission', '2025-09-01', '2025-08-15', 'https://bpsc.bih.nic.in', 'Upcoming', 'sarkariresult.com', true),
('RPSC RAS Prelims 2025 Admit Card', 'Rajasthan Public Service Commission', '2025-08-10', '2025-07-25', 'https://rpsc.rajasthan.gov.in', 'Upcoming', 'sarkariresult.com', true),
('Delhi Police Constable 2025 Admit Card', 'Staff Selection Commission', '2025-06-20', '2025-06-05', 'https://ssc.nic.in', 'Upcoming', 'sarkariresult.com', true),
('UPPSC PCS Prelims 2025 Admit Card', 'UP Public Service Commission', '2025-06-15', '2025-06-01', 'https://uppsc.up.nic.in', 'Upcoming', 'sarkariresult.com', true)
ON CONFLICT DO NOTHING;

-- Insert 15 new verified scholarships
INSERT INTO verified_scholarships (name, provider, amount, eligibility_summary, apply_url, source_url, source, official_domain, required_documents, status, target_academic_level, target_locations, category_criteria, income_criteria, minimum_percentage) VALUES
('Prime Minister Special Scholarship Scheme (PMSSS)', 'AICTE - Government of India', 'Up to Rs. 1,25,000/year', 'Domicile of J&K and Ladakh, 12th passed', 'https://aicte-jk-scholarship-gov.in', 'https://aicte-jk-scholarship-gov.in', 'Government Portal', 'aicte-jk-scholarship-gov.in', ARRAY['Domicile Certificate', '12th Marksheet', 'Aadhaar Card', 'Income Certificate'], 'active', ARRAY['Undergraduate'], ARRAY['Jammu & Kashmir', 'Ladakh'], ARRAY['All Categories'], 'Rs. 8 Lakh per annum', 50),
('KVPY Fellowship - Kishore Vaigyanik Protsahan Yojana', 'Department of Science & Technology', 'Rs. 5,000-7,000/month + Contingency', 'Students in Class 11 to 1st year B.Sc', 'https://kvpy.iisc.ac.in', 'https://kvpy.iisc.ac.in', 'Government Portal', 'kvpy.iisc.ac.in', ARRAY['School ID Card', 'Marksheets', 'Aadhaar Card'], 'active', ARRAY['Class 11', 'Class 12', 'Undergraduate'], ARRAY['All India'], ARRAY['All Categories'], 'No income limit', 60),
('INSPIRE Scholarship - Innovation in Science', 'Department of Science & Technology', 'Rs. 80,000/year for 5 years', 'Top 1% in Class 12 board exam pursuing science', 'https://online-inspire.gov.in', 'https://online-inspire.gov.in', 'Government Portal', 'online-inspire.gov.in', ARRAY['12th Marksheet', 'College Admission Proof', 'Aadhaar Card', 'Bank Details'], 'active', ARRAY['Undergraduate'], ARRAY['All India'], ARRAY['All Categories'], 'No income limit', 0),
('Maulana Azad National Fellowship (MANF)', 'Ministry of Minority Affairs', 'Rs. 31,000/month (JRF) + Rs. 35,000/month (SRF)', 'Minority community students for M.Phil/PhD', 'https://scholarships.gov.in', 'https://scholarships.gov.in', 'National Scholarship Portal', 'scholarships.gov.in', ARRAY['Minority Certificate', 'UGC NET/JRF Qualification', 'Aadhaar Card', 'Income Certificate'], 'active', ARRAY['M.Phil', 'PhD'], ARRAY['All India'], ARRAY['Minorities'], 'Rs. 6 Lakh per annum', 55),
('Swami Vivekananda Single Girl Child Scholarship', 'UGC', 'Rs. 36,200/year', 'Single girl child pursuing research (M.Phil/PhD)', 'https://scholarships.gov.in', 'https://scholarships.gov.in', 'UGC Portal', 'ugc.ac.in', ARRAY['Single Girl Child Affidavit', 'Admission Letter', 'Aadhaar Card'], 'active', ARRAY['M.Phil', 'PhD'], ARRAY['All India'], ARRAY['All Categories - Single Girl Child'], 'No income limit', 55),
('Begum Hazrat Mahal National Scholarship', 'Maulana Azad Education Foundation', 'Rs. 5,000-6,000/year', 'Minority girls in Class 9-12', 'https://bhmnsmaef.org', 'https://bhmnsmaef.org', 'MAEF Portal', 'bhmnsmaef.org', ARRAY['Minority Certificate', 'Marksheet', 'Income Certificate', 'Aadhaar Card'], 'active', ARRAY['Class 9', 'Class 10', 'Class 11', 'Class 12'], ARRAY['All India'], ARRAY['Minorities - Girls Only'], 'Rs. 2 Lakh per annum', 50),
('AICTE Saksham Scholarship for Differently Abled', 'AICTE', 'Rs. 50,000/year', 'Differently abled students in technical education', 'https://aicte-india.org', 'https://aicte-india.org', 'AICTE Portal', 'aicte-india.org', ARRAY['Disability Certificate', 'Admission Letter', 'Aadhaar Card', 'Income Certificate'], 'active', ARRAY['Diploma', 'Undergraduate'], ARRAY['All India'], ARRAY['Differently Abled'], 'Rs. 8 Lakh per annum', 50),
('Tata Trusts Education Scholarship', 'Tata Trusts', 'Up to Rs. 50,000/year', 'Students from economically weaker sections', 'https://tatatrusts.org', 'https://tatatrusts.org', 'Tata Trusts', 'tatatrusts.org', ARRAY['Income Certificate', 'Marksheets', 'Admission Letter', 'Aadhaar Card'], 'active', ARRAY['Undergraduate', 'Postgraduate'], ARRAY['All India'], ARRAY['All Categories'], 'Rs. 2.5 Lakh per annum', 60),
('Reliance Foundation Scholarship', 'Reliance Foundation', 'Up to Rs. 2,00,000/year', 'Meritorious students in UG programs', 'https://reliancefoundation.org', 'https://reliancefoundation.org', 'Reliance Foundation', 'reliancefoundation.org', ARRAY['12th Marksheet', 'Admission Proof', 'Aadhaar Card', 'Income Certificate'], 'active', ARRAY['Undergraduate'], ARRAY['All India'], ARRAY['All Categories'], 'Rs. 15 Lakh per annum', 60),
('Kotak Kanya Scholarship', 'Kotak Mahindra Group', 'Rs. 1,50,000/year', 'Meritorious girl students from underprivileged backgrounds', 'https://kotakeducation.org', 'https://kotakeducation.org', 'Kotak Education Foundation', 'kotakeducation.org', ARRAY['12th Marksheet', 'Income Certificate', 'Aadhaar Card', 'College Fee Receipt'], 'active', ARRAY['Undergraduate'], ARRAY['All India'], ARRAY['Girls Only'], 'Rs. 3.6 Lakh per annum', 75),
('L&T Build India Scholarship', 'Larsen & Toubro', 'Up to Rs. 2,00,000/year', 'Engineering students with excellent academics', 'https://lntbuildindiascholarship.com', 'https://lntbuildindiascholarship.com', 'L&T Corporate', 'lntbuildindiascholarship.com', ARRAY['JEE Score Card', 'Admission Letter', 'Income Certificate', 'Aadhaar Card'], 'active', ARRAY['Undergraduate'], ARRAY['All India'], ARRAY['All Categories - Engineering'], 'Rs. 6 Lakh per annum', 0),
('Sitaram Jindal Foundation Scholarship', 'Sitaram Jindal Foundation', 'Rs. 1,500-11,000/month', 'Students from Class 1 to PhD level', 'https://sitaramjindalfoundation.org', 'https://sitaramjindalfoundation.org', 'Jindal Foundation', 'sitaramjindalfoundation.org', ARRAY['Marksheets', 'Income Certificate', 'Aadhaar Card', 'Admission Proof'], 'active', ARRAY['School', 'Undergraduate', 'Postgraduate', 'PhD'], ARRAY['All India'], ARRAY['All Categories'], 'Rs. 2.5 Lakh per annum', 60),
('Indira Gandhi Scholarship for Single Girl Child', 'UGC', 'Rs. 36,200/year for 2 years', 'Single girl child admitted to PG program', 'https://ugc.ac.in', 'https://ugc.ac.in', 'UGC Portal', 'ugc.ac.in', ARRAY['Single Girl Child Affidavit', 'PG Admission Proof', 'Aadhaar Card', 'Marksheets'], 'active', ARRAY['Postgraduate'], ARRAY['All India'], ARRAY['Single Girl Child'], 'No income limit', 0),
('Fair & Lovely (Glow & Lovely) Career Foundation Scholarship', 'Hindustan Unilever Foundation', 'Rs. 50,000', 'Women pursuing graduation after Class 12', 'https://glowandlovelycareers.in', 'https://glowandlovelycareers.in', 'HUL Foundation', 'glowandlovelycareers.in', ARRAY['12th Marksheet', 'Income Certificate', 'Aadhaar Card', 'Admission Letter'], 'active', ARRAY['Undergraduate'], ARRAY['All India'], ARRAY['Women Only'], 'Rs. 6 Lakh per annum', 0),
('Ishan Uday Scholarship for NE Region', 'UGC', 'Rs. 5,400/month (General) or Rs. 7,800/month (Technical)', 'Students from North-Eastern states in UG/PG', 'https://ugc.ac.in', 'https://ugc.ac.in', 'UGC Portal', 'ugc.ac.in', ARRAY['Domicile Certificate', 'Marksheets', 'Aadhaar Card', 'Admission Proof'], 'active', ARRAY['Undergraduate', 'Postgraduate'], ARRAY['Arunachal Pradesh', 'Assam', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Sikkim', 'Tripura'], ARRAY['All Categories - NE Region'], 'No income limit', 0)
ON CONFLICT DO NOTHING;

-- Also insert some into the main scholarships table
INSERT INTO scholarships (title, description, eligibility_criteria, type, amount, deadline, application_link, verified) VALUES
('PM Scholarship Scheme for RPF/RPSF', 'Scholarship for wards of RPF/RPSF personnel for professional degree courses', 'Ward of RPF/RPSF personnel, pursuing professional degree', 'government', 25000, '2025-10-31', 'https://scholarships.gov.in', true),
('Post Matric Scholarship for OBC Students', 'Central government scholarship for OBC students studying post-matric', 'OBC category, family income below Rs. 1 Lakh', 'government', 7500, '2025-11-30', 'https://scholarships.gov.in', true),
('HDFC Badhte Kadam Scholarship', 'Scholarship for underprivileged students pursuing higher education', 'Family income below Rs. 2.5 Lakh, 60% marks in previous exam', 'private', 35000, '2025-09-30', 'https://hdfcbank.com/csr', true),
('Wipro Earthian Sustainability Scholarship', 'For students demonstrating commitment to sustainability', 'UG/PG students with sustainability projects', 'private', 50000, '2025-12-15', 'https://wipro.com/earthian', true),
('Narotam Sekhsaria Foundation Scholarship', 'Loan scholarship for PG studies in India and abroad', 'Indian national, admitted to PG program', 'ngo', 2000000, '2025-08-31', 'https://nfrp.org', true),
('KC Mahindra Scholarship for Post Graduate Studies Abroad', 'Interest-free loan scholarship for studying abroad', 'Indian national with PG admission abroad', 'private', 500000, '2025-04-30', 'https://kcmahindrascholarships.org', true),
('ONGC Scholarship for SC/ST Students', 'Scholarship for SC/ST students in engineering and medical', 'SC/ST category pursuing engineering/medical', 'government', 48000, '2025-10-31', 'https://ongcindia.com', true),
('Google Generation Scholarship', 'For students in computer science and related fields', 'UG/PG students in CS with strong academics', 'private', 75000, '2025-12-01', 'https://buildyourfuture.withgoogle.com', true),
('Azim Premji Foundation Fellowship', 'Fellowship for working in education sector', 'Graduates committed to education development', 'ngo', 300000, '2025-07-31', 'https://azimpremjifoundation.org', true),
('Dr. Ambedkar Foundation Scholarship', 'Merit-based scholarship for SC/ST students', 'SC/ST students with 60%+ marks in Class 12', 'government', 100000, '2025-09-15', 'https://ambedkarfoundation.nic.in', true)
ON CONFLICT DO NOTHING;
