// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aanuxmipcjiqcmlqfdjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhbnV4bWlwY2ppcWNtbHFmZGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5MDk0NTQsImV4cCI6MjA3NjQ4NTQ1NH0.PpuyzLQM_K3j7rrdBuKbHciN2-xMt4RdrXtx4xOGLFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});